package com.restaurant.pos.model;

public enum AuditEventType {
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
    ACCOUNT_LOCKED,
    LOGOUT,
    ORDER_PLACED,
    ORDER_VOIDED,
    MENU_ITEM_CREATED,
    MENU_ITEM_UPDATED,
    MENU_ITEM_AVAILABILITY_CHANGED,
    CATEGORY_CREATED,
    CATEGORY_UPDATED,
    CATEGORY_DELETED,
    SETTINGS_CHANGED,
    USER_CREATED,
    USER_UPDATED,
    USER_PASSWORD_RESET,
    USER_ENABLED,
    USER_DISABLED,
    BACKUP_CREATED,
    BACKUP_RESTORED,
    APPLICATION_ERROR,
    SECURITY_VIOLATION
}
